# Generated by Django 4.2.28 on 2026-03-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0004_project_requirementsession_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementsession",
            name="phase",
            field=models.CharField(
                choices=[
                    ("collecting", "需求收集中"),
                    ("organizing", "需求整理中"),
                    ("completed", "已完成"),
                ],
                default="collecting",
                max_length=20,
                verbose_name="会话阶段",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="path",
            field=models.CharField(
                help_text="项目根目录路径，需求文档将保存到该目录下的 doc/01-or 文件夹",
                max_length=500,
                verbose_name="项目路径",
            ),
        ),
    ]
