# Generated by Django 4.2.28 on 2026-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0005_requirementsession_phase_alter_project_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_images/", verbose_name="上传图片"
            ),
        ),
    ]
