# Generated by Django 5.2.11 on 2026-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0006_requirementmessage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirementmessage",
            name="image",
        ),
        migrations.AddField(
            model_name="requirementmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat_attachments/",
                verbose_name="上传附件",
            ),
        ),
    ]
