# Generated by Django 5.2.11 on 2026-03-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0007_remove_requirementmessage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "model_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="模型 ID"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
            ],
            options={
                "verbose_name": "大模型",
                "verbose_name_plural": "大模型",
                "ordering": ["provider", "-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="厂商名称"
                    ),
                ),
                (
                    "api_key_env",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="API Key 环境变量名"
                    ),
                ),
            ],
            options={
                "verbose_name": "大模型厂商",
                "verbose_name_plural": "大模型厂商",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="llm_model",
            field=models.ForeignKey(
                blank=True,
                help_text="项目默认使用的大语言模型，不设置则使用系统默认模型",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collector.llmmodel",
                verbose_name="默认大模型",
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="collector.llmprovider",
                verbose_name="厂商",
            ),
        ),
    ]
