# Generated by Django 5.2.11 on 2026-03-02 08:34

from django.db import migrations

def seed_llm_data(apps, schema_editor):
    LLMProvider = apps.get_model('collector', 'LLMProvider')
    LLMModel = apps.get_model('collector', 'LLMModel')

    # 创建厂商
    ali_provider, _ = LLMProvider.objects.get_or_create(
        name="阿里",
        defaults={'api_key_env': 'QWEN_API_KEY'}
    )

    # 创建模型
    models_to_seed = [
        {'provider': ali_provider, 'name': 'Qwen Turbo', 'model_id': 'qwen-turbo', 'is_default': True},
        {'provider': ali_provider, 'name': 'Qwen Plus', 'model_id': 'qwen-plus', 'is_default': False},
        {'provider': ali_provider, 'name': 'Qwen Max', 'model_id': 'qwen-max', 'is_default': False},
    ]

    for model_data in models_to_seed:
        LLMModel.objects.get_or_create(**model_data)

class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0008_llmmodel_llmprovider_project_llm_model_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_llm_data),
    ]
