# Generated by Django 5.2.11 on 2026-03-02 08:50

from django.db import migrations

def update_llm_models(apps, schema_editor):
    LLMProvider = apps.get_model('collector', 'LLMProvider')
    LLMModel = apps.get_model('collector', 'LLMModel')

    # 获取“阿里”厂商
    ali_provider = LLMProvider.objects.filter(name="阿里").first()

    if ali_provider:
        # 要添加或更新的模型列表
        models_to_seed = [
            {'provider': ali_provider, 'name': 'Qwen VL Plus', 'model_id': 'qwen-vl-plus', 'is_default': False},
            {'provider': ali_provider, 'name': 'Qwen VL Max', 'model_id': 'qwen-vl-max', 'is_default': False},
            {'provider': ali_provider, 'name': 'Qwen Long', 'model_id': 'qwen-long', 'is_default': False},
        ]

        for model_data in models_to_seed:
            LLMModel.objects.update_or_create(
                model_id=model_data['model_id'],
                defaults=model_data
            )

class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0009_auto_20260302_1634"),
    ]

    operations = [
        migrations.RunPython(update_llm_models),
    ]
