# Generated by Django 5.2.12 on 2026-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_seed_builtin_ali_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dingtalk', '钉钉'), ('wecom', '企业微信'), ('feishu', '飞书')], max_length=20, verbose_name='通信平台')),
                ('name', models.CharField(help_text='同一通信平台内唯一', max_length=100, verbose_name='配置名称')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置内容')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通信配置',
                'verbose_name_plural': '通信配置',
                'ordering': ['provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'name'), name='uniq_provider_name')],
            },
        ),
    ]
