# Generated by Django 5.2.12 on 2026-03-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_communicationchannelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSystemParamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名')),
                ('component_key', models.CharField(max_length=200, verbose_name='组件标识')),
                ('config_name', models.CharField(help_text='同一组件内唯一，如 test/prod', max_length=100, verbose_name='配置名')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数值')),
                ('schema_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Schema 快照')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '组件系统参数配置',
                'verbose_name_plural': '组件系统参数配置',
                'ordering': ['module_name', 'component_key', 'config_name'],
                'constraints': [models.UniqueConstraint(fields=('component_key', 'config_name'), name='uniq_component_config_name')],
            },
        ),
    ]
