# Generated by Django 5.2.12 on 2026-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0013_componentsystemparamconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentSystemPermissionGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_name", models.CharField(max_length=100, verbose_name="模块名")),
                ("component_key", models.CharField(max_length=200, verbose_name="组件标识")),
                ("permission_key", models.CharField(max_length=200, verbose_name="权限标识")),
                ("permission_name", models.CharField(blank=True, max_length=200, verbose_name="权限名称")),
                ("is_granted", models.BooleanField(default=False, verbose_name="是否已授予")),
                ("grant_note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "组件系统权限确认",
                "verbose_name_plural": "组件系统权限确认",
                "ordering": ["module_name", "component_key", "permission_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component_key", "permission_key"),
                        name="uniq_component_permission_key",
                    )
                ],
            },
        ),
    ]
