# Generated by Django 5.2.12 on 2026-03-14 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_companionprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReplyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '生成中'), ('completed', '已完成'), ('stopped', '已停止'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('stop_requested', models.BooleanField(default=False, verbose_name='是否请求停止')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_tasks_as_reply', to='collector.requirementmessage', verbose_name='助手消息')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reply_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_tasks', to='collector.requirementsession', verbose_name='所属会话')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_tasks_as_prompt', to='collector.requirementmessage', verbose_name='用户消息')),
            ],
            options={
                'verbose_name': '聊天回复任务',
                'verbose_name_plural': '聊天回复任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
