# Generated by Django 5.2.12 on 2026-03-14 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_alter_requirementmessage_role_chatreplytask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider_name', models.CharField(max_length=100, verbose_name='厂商名称')),
                ('base_url', models.CharField(blank=True, max_length=300, verbose_name='API Base URL')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API Key')),
                ('default_model_id', models.CharField(blank=True, max_length=120, verbose_name='默认模型 ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_api_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '大模型 API 配置',
                'verbose_name_plural': '大模型 API 配置',
                'ordering': ['-updated_at', 'name'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'name'), name='uniq_user_llm_api_config_name')],
            },
        ),
        migrations.CreateModel(
            name='LocalLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('endpoint', models.CharField(default='http://127.0.0.1:11434', max_length=300, verbose_name='Ollama 地址')),
                ('model_name', models.CharField(max_length=120, verbose_name='模型名称')),
                ('keep_alive', models.CharField(default='5m', max_length=32, verbose_name='keep_alive')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '本地大模型配置',
                'verbose_name_plural': '本地大模型配置',
                'ordering': ['-updated_at', 'name'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'name'), name='uniq_user_local_llm_config_name')],
            },
        ),
    ]
