# Generated by Django 5.2.12 on 2026-03-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_localllmconfig_runtime_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionprofile',
            name='backup_model_tokens',
            field=models.JSONField(blank=True, default=list, verbose_name='备用模型列表'),
        ),
        migrations.AddField(
            model_name='companionprofile',
            name='llm_routing_mode',
            field=models.CharField(choices=[('manual', '手动模式'), ('auto', '自动模式')], default='manual', max_length=20, verbose_name='模型路由模式'),
        ),
    ]
