# Generated by Django 5.2.12 on 2026-03-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_companionprofile_backup_model_tokens_and_more'),
        ('collector', '0022_companionprofile_llm_routing_backup'),
    ]

    operations = [
    ]
