# Generated by Django 5.2.12 on 2026-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_companionprofile_permission_granularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRuntimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, verbose_name='设置键')),
                ('value_text', models.TextField(blank=True, default='', verbose_name='设置值')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统运行时设置',
                'verbose_name_plural': '系统运行时设置',
                'ordering': ['key'],
            },
        ),
    ]
