# Generated by Django 5.2.11 on 2026-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0026_systemruntimesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="companionprofile",
            name="adapter_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="adapter 专属配置参数，JSON 格式",
                verbose_name="adapter 配置",
            ),
        ),
        migrations.AddField(
            model_name="companionprofile",
            name="adapter_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="外部 agent adapter 类型标识，如 process、http；空值表示不使用 adapter",
                max_length=40,
                verbose_name="adapter 类型",
            ),
        ),
    ]
